version: "3.8"
services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TELEGRAM_HELPER_DB_USERNAME}
      - POSTGRES_PASSWORD=${TELEGRAM_HELPER_DB_PASSWORD}
      - POSTGRES_DB=${TELEGRAM_HELPER_DB_NAME}
    ports:
      - ${TELEGRAM_HELPER_DB_PORT}:${TELEGRAM_HELPER_DB_PORT}
  telegram_helper_wellcum:
    image: telegram_helper_wellcum
    volumes:
      - ./telegram_helper_home:/opt/telegram_helper_home
    environment:
      - TELEGRAM_HELPER_BOT_NAME=${TELEGRAM_HELPER_BOT_NAME}
      - TELEGRAM_HELPER_BOT_TOKEN=${TELEGRAM_HELPER_BOT_TOKEN}
      - TELEGRAM_HELPER_ADMIN_USERNAME=${TELEGRAM_HELPER_ADMIN_USERNAME}
      - TELEGRAM_HELPER_FEEDBACK_CHANNEL_ID=${TELEGRAM_HELPER_FEEDBACK_CHANNEL_ID}
      - TELEGRAM_HELPER_FEEDBACK_CHANNEL_CHAT_ID=${TELEGRAM_HELPER_FEEDBACK_CHANNEL_CHAT_ID}
      - TELEGRAM_HELPER_DB_HOST=${TELEGRAM_HELPER_DB_HOST}
      - TELEGRAM_HELPER_DB_PORT=${TELEGRAM_HELPER_DB_PORT}
      - TELEGRAM_HELPER_DB_NAME=${TELEGRAM_HELPER_DB_NAME}
      - TELEGRAM_HELPER_DB_USERNAME=${TELEGRAM_HELPER_DB_USERNAME}
      - TELEGRAM_HELPER_DB_PASSWORD=${TELEGRAM_HELPER_DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${TELEGRAM_HELPER_PORT}:${TELEGRAM_HELPER_PORT}